version: '3.7'

x-common:
  &common
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "3"

services:

  # SSL Certificate
  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: on-failure
    environment:
      DOMAIN: '${DOMAIN}'
      EMAIL: '${EMAIL}'
    command: certonly --standalone --quiet -d ${DOMAIN} --agree-tos --email ${EMAIL}
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./volume/certs/:/etc/letsencrypt/live/
      - ./volume/letsencrypt/etc/:/etc/letsencrypt
      - ./volume/letsencrypt/var/lib/:/var/lib/letsencrypt
      - ./volume/letsencrypt/var/log/:/var/log/letsencrypt

  registry:
    <<: *common
    container_name: registry
    image: registry:2.7
    restart: always
    ports:
      - ${REGISTRY_PORT}:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_STORAGE_DELETE_ENABLED: 'false'
      # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
      # REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
    depends_on:
      - certbot
    volumes:
      - ./volume/data:/data
      - /etc/letsencrypt/live/registry.keivanipchihagh.com/fullchain.pem:/certs/fullchain.pem/
      - /etc/letsencrypt/live/registry.keivanipchihagh.com/privkey.pem/:/certs/privkey.pem
    networks:
      - nginx

  registry-ui:
    <<: *common
    container_name: registry-ui
    image: jc21/registry-ui:2.0.0
    restart: always
    ports:
      - ${REGISTRY_UI_PORT}:80
    environment:
      REGISTRY_HOST: registry:5000
      REGISTRY_DOMAIN: ${DOMAIN}
      REGISTRY_STORAGE_DELETE_ENABLED: 1
      REGISTRY_SSL: 'false'
    depends_on:
      - registry
    networks:
      - nginx

networks:
  nginx:
    name: nginx
    internal: true
