version: '3.7'

x-common:
  &common
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "3"

services:

  # Registry
  registry:
    <<: *common
    container_name: registry
    image: registry:2.8
    restart: always
    ports:
      - ${REGISTRY_PORT}:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      # REGISTRY_AUTH: 'htpasswd'
      # REGISTRY_AUTH_HTPASSWD_REALM: 'Registry Realm'
      # \REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - ./volume/registry/data:/data
      - ./volume/registry/auth:/auth
    networks:
      - nginx

  # Registry-UI
  registry-ui:
    <<: *common
    container_name: registry-ui
    image: jc21/registry-ui:2.0.2
    restart: always
    ports:
      - ${REGISTRY_UI_PORT:-4012}:80
    environment:
      REGISTRY_HOST: registry:${REGISTRY_PORT:-5000}
      REGISTRY_DOMAIN: ${DOMAIN}
      REGISTRY_STORAGE_DELETE_ENABLED: 1
      REGISTRY_SSL: 'false' # No certbot, nginx SSL
    depends_on:
      - registry
    networks:
      - nginx

networks:
  nginx:
    name: nginx
    internal: true
