version: "3.7"

x-common:
  &common
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "3"

services:

  # Grafana
  grafana:
    <<: *common
    image: grafana/grafana-enterprise:9.3.6
    container_name: grafana
    restart: always
    user: "$UID:$GID"
    ports:
      - ${GF_PORT:-3000}:3000
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: ${GF_USERS_ALLOW_SIGN_UP:-false}
      GF_AUTH_DISABLE_LOGIN_FORM: ${GF_AUTH_DISABLE_LOGIN_FORM:-false}
    volumes:
      - ./volume/grafana:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/config.ini:/etc/grafana/config.ini
      # - ./grafana/dashboards:/var/lib/grafana/dashboards # custom dashboards
    networks:
      - nginx
      - private

  # Prometheus
  prometheus:
    <<: *common
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    restart: always
    user: "$UID:$GID"
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./volume/prometheus:/prometheus
    networks:
      - nginx
      - private

  # Node Exporter
  node-exporter:
    <<: *common
    image: prom/node-exporter:v1.5.0
    container_name: node-exporter
    restart: always
    ports:
      - ${NODE_PORT:-9100}:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    networks:
      - private

  # Cadvisor
  cadvisor:
    <<: *common
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    privileged: true
    restart: always
    devices:
      - /dev/kmsg:/dev/kmsg
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro  # Linux only
    ports:
      - ${CADVISOR_PORT:-8080}:8080
    networks:
      - private

  # AlertManager
  alertmanager:
    <<: *common
    container_name: alertmanager
    image: prom/alertmanager:v0.25.0
    restart: unless-stopped
    ports:
      - ${ALERTMANAGER_PORT:-9093}:9093
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    volumes:
      - ./alertmanager:/config
      - ./volume/alertmanager:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug
    networks:
      - private
      - nginx


networks:
  nginx:
    name: nginx
    external: true
  private:
    name: private
    internal: true
