version: '3.7'

services:

  # SSL Certificate
  certbot:
    container_name: certbot
    image: certbot/certbot
    command: certonly --standalone --quiet -d ${DOMAIN} --agree-tos --email ${EMAIL}
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - ./volume/certs/:/etc/letsencrypt/live/
      - ./volume/letsencrypt/etc/:/etc/letsencrypt
      - ./volume/letsencrypt/var/lib/:/var/lib/letsencrypt
      - ./volume/letsencrypt/var/log/:/var/log/letsencrypt

  # Management Panel
  xui:
    container_name: xui
    image: registry.keivanipchihagh.com/x-ui:beta
    restart: unless-stopped
    # depends_on:
    #  - certbot
    volumes:
        - ./volume/db/:/etc/x-ui
        - /etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/root/certs/${DOMAIN}/fullchain.pem
        - /etc/letsencrypt/live/${DOMAIN}/privkey.pem:/root/certs/${DOMAIN}/privkey.pem
    network_mode: host
