apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: monitoring
spec:
#  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/monitoring"
