version: '3.7'

x-common:
  &common
  image: apache/airflow:2.3.0
  user: "${AIRFLOW_UID:-0}:0"
  environment:
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT:-5432}/airflow"
    AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS: "False"
    _AIRFLOW_DB_UPGRADE: "True"
    AIRFLOW__CORE__LOGGING_LEVEL: "INFO"
  env_file: 
    - ../.env
  volumes:
    - ./airflow-data/dags:/opt/airflow/dags
    - ./airflow-data/logs:/opt/airflow/logs
    - ./airflow-data/plugins:/opt/airflow/plugins
    - /var/run/docker.sock:/var/run/docker.sock
  networks:
    - airflow
    - services

x-depends-on:
  &depends-on
  depends_on:
    airflow-init:
      condition: service_completed_successfully

services:

  # Airflow Scheduler
  airflow-scheduler:
    <<: *common
    <<: *depends-on
    container_name: airflow-scheduler
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5
    command: scheduler
    restart: on-failure

    ports:
      - "${AIRFLOW_SCHEDULER_PORT}:8793"

  # Airflow Webserver
  airflow-webserver:
    <<: *common
    <<: *depends-on
    container_name: airflow-webserver
    restart: always
    command: webserver

    ports:
      - "${AIRFLOW_WEBSERVER_PORT:-8085}:8080"

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 3
  
  # Airflow Initializer
  airflow-init:
    <<: *common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version


networks:
  services:
    name: services
    external: true
  airflow:
    name: airflow
    internal: true
