apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: hashicorp
spec:
  storageClassName: longhorn
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/vault"
