version: '3.7'

x-common:
  &common
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "3"
  networks:
    - private

services:

  # Postgres Server
  postgres:
    <<: *common
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB:-postgres}", "-U", "${POSTGRES_USER:-postgres}"]
      timeout: 10s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
      # Run SQL initiallization scripts (e.g. create database, create user, etc.) - NOTE: this will only run if the database is empty
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  # pgadmin4
  pgadmin:
    <<: *common
    container_name: pgadmin
    image: dpage/pgadmin4:7.0
    restart: unless-stopped
    user: "$UID:$GID"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: '${PGADMIN_CONFIG_SERVER_MODE:-False}'  # Production Mode
    volumes:
       - ./volume/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - nginx
      - private

  # Postgres Exporter
  postgres-exporter:
    <<: *common
    image: wrouesnel/postgres_exporter:v0.8.0
    container_name: postgres-exporter
    restart: always
    ports:
      - ${POSTGRES_EXPORTER_PORT:-9187}:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}?sslmode=${POSTGRES_SSL:-disable}"


networks:
  nginx:
    name: nginx
    internal: true
  private:
    name: private
    internal: true
