version: "3.9"

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:github-pr-2816
    restart: unless-stopped # Ensure proxy manager survives crashes
    ports:
      - "${NPM_HTTP_PORT:-80}:80"     # HTTP port
      - "${NPM_UI_PORT:-81}:81"       # Admin UI
      - "${NPM_HTTPS_PORT:-443}:443"  # HTTPS port
    volumes:
      - ./volume/data:/data
      - ./volume/letsencrypt:/etc/letsencrypt
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      timeout: 3s
      interval: 10s
    networks:
      - nginx

networks:
  nginx:
    name: nginx
    internal: true
